# Stub for yarbo-data-sdk package root.
# The SDK ships Python source (no .pyi files). This stub supplements what
# pyright can infer, covering instance attributes set in __init__ without
# annotations, and re-exporting top-level symbols used by the integration.

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from yarbo_robot_sdk.exceptions import (
    AuthenticationError as AuthenticationError,
    TokenExpiredError as TokenExpiredError,
    YarboSDKError as YarboSDKError,
)
from yarbo_robot_sdk.models import (
    ControlFieldDefinition as ControlFieldDefinition,
    Device as Device,
    FieldDefinition as FieldDefinition,
)
from yarbo_robot_sdk.modules import (
    BoundYarboDevice as BoundYarboDevice,
    CoreModule as CoreModule,
)
from yarbo_robot_sdk.mqtt_client import MqttClient as MqttClient

def get_field_definitions(type_id: str) -> list[FieldDefinition]: ...
def get_control_field_definitions(type_id: str) -> list[ControlFieldDefinition]: ...

class YarboClient:
    token: str | None
    refresh_token: str | None
    core: CoreModule

    def __init__(self, api_base_url: str | None = ...) -> None: ...
    def login(self, username: str, password: str) -> None: ...
    def restore_session(
        self, username: str, token: str, refresh_token: str
    ) -> None: ...
    def close(self) -> None: ...
    def get_devices(self) -> list[Device]: ...
    def device(
        self, device: Device, data: dict[str, Any] | None = ...
    ) -> BoundYarboDevice: ...
    def get_connect_wifi_name(
        self, sn: str, type_id: str, timeout: float = ...
    ) -> dict[str, Any]: ...
    def get_device_msg(
        self, sn: str, type_id: str, timeout: float = ...
    ) -> dict[str, Any]: ...
    def get_map(
        self, sn: str, type_id: str, timeout: float = ...
    ) -> dict[str, Any]: ...
    def read_all_plan(
        self, sn: str, type_id: str, timeout: float = ...
    ) -> dict[str, Any]: ...
    def read_gps_ref(
        self, sn: str, type_id: str, timeout: float = ...
    ) -> dict[str, Any]: ...
    def mqtt_connect(self) -> None: ...
    def mqtt_disconnect(self) -> None: ...
    def mqtt_publish_command(
        self, sn: str, type_id: str, command_topic_name: str, payload: dict[str, Any]
    ) -> None: ...
    def subscribe_device_message(
        self, sn: str, type_id: str, callback: Callable[[str, dict[str, Any]], Any]
    ) -> None: ...
    def subscribe_heart_beat(
        self, sn: str, type_id: str, callback: Callable[[str, dict[str, Any]], Any]
    ) -> None: ...
    def subscribe_data_feedback(
        self,
        sn: str,
        type_id: str,
        callback: Callable[[str, dict[str, Any]], Any] | None = ...,
    ) -> None: ...
    def request_with_feedback(
        self,
        sn: str,
        type_id: str,
        command_topic_name: str,
        payload: dict[str, Any],
        response_topic_filter: str,
        timeout: float = ...,
    ) -> dict[str, Any]: ...
    def _ensure_mqtt_for(self, sn: str) -> MqttClient: ...
