from typing import Any

def extract_field(data: dict[str, Any], field_path: str) -> Any: ...
def convert_local_to_gps(
    ref_lat: float, ref_lon: float, local_x: float, local_y: float
) -> tuple[float, float]: ...
def convert_map_to_geojson(
    map_data: dict[str, Any], fallback_ref: dict[str, Any] | None = ...
) -> dict[str, Any]: ...
def extract_active_network(route_priority: object) -> str | None: ...
