name: "Release assets"

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  COMPONENT: yarbo_bg

jobs:
  artifacts:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - name: "Check out repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Zip component dir"
        run: zip -r ${{ env.COMPONENT }}-${{ github.ref_name }}.zip custom_components/${{ env.COMPONENT }}

      - name: "Upload release asset"
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: ${{ env.COMPONENT }}-${{ github.ref_name }}.zip
