name: "Release assets"

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  COMPONENT: yarbo

jobs:
  artifacts:
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - name: "Check out repository"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: "Zip component dir"
        run: zip -r ${{ env.COMPONENT }}-${{ github.ref_name }}.zip custom_components/${{ env.COMPONENT }}

      - name: "Upload release asset"
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: ${{ env.COMPONENT }}-${{ github.ref_name }}.zip
